### ISSUE TITLE
SProp: set tactic does broken things

### ISSUE THREAD

**Issue by SkySkimmer** [SkySkimmer/coq#13]
Reported by @kyoDralliam on gitter
~~~coq
Goal forall (P Q : SProp), P -> Q.
Proof.
  intros P Q H. set (H0 := H).
  (* goal is now H0 *)
~~~

@ppedrot I know you know things about `set` WDYT?

**Comment by ppedrot** [comment]
Yeah, you need to check that the irrelevance of the terms need the same when converting in the kernel, because the typing invariant is not preserved. If I were you I'd just put a wrapper to do that.

**Comment by SkySkimmer** [comment]
Fixed.
